disable system tests when Python is missing

diff --git a/systemtests/Makefile.am b/systemtests/Makefile.am
--- a/systemtests/Makefile.am
+++ b/systemtests/Makefile.am
@@ -12,15 +12,20 @@ clean-local:
 	rm -rf $(SYSTEMTESTS_LOGS_DIR)
 
 check:
-	@echo "Checking systemtests UT's..."
-	$(PYTHON) -m unittest discover -v $(SYSTEMTESTS_SRC_DIR)
-
-	@echo "Running systemtests..."
-	robot -d $(SYSTEMTESTS_LOGS_DIR) \
-              --variable SUT_PATH:$(top_builddir)/src/omtt \
-              --variable OMTT_TESTS_DIR:$(SYSTEMTESTS_SRC_DIR)/omtt \
-              --variable HELPER_APPS_DIR:$(SYSTEMTESTS_BUILD_DIR)/apps \
-              -L DEBUG \
-              $(SYSTEMTESTS_SRC_DIR)
+	@if [ "$(PYTHON)" = ":" ] ; then                                       \
+		echo "Python not found, not able to execute system tests." ;   \
+		exit 1 ;                                                       \
+	else                                                                   \
+		echo "Checking systemtests UT's..." ;                          \
+		$(PYTHON) -m unittest discover -v $(SYSTEMTESTS_SRC_DIR) ;     \
+                                                                               \
+		echo "Running systemtests..." ;                                \
+		robot -d $(SYSTEMTESTS_LOGS_DIR)                               \
+                      --variable SUT_PATH:$(top_builddir)/src/omtt             \
+                      --variable OMTT_TESTS_DIR:$(SYSTEMTESTS_SRC_DIR)/omtt    \
+                      --variable HELPER_APPS_DIR:$(SYSTEMTESTS_BUILD_DIR)/apps \
+                      -L DEBUG                                                 \
+                      $(SYSTEMTESTS_SRC_DIR) ;                                 \
+	fi
 
 .PHONY: check
