check for pyhon unittest module

diff --git a/systemtests/Makefile.am b/systemtests/Makefile.am
--- a/systemtests/Makefile.am
+++ b/systemtests/Makefile.am
@@ -13,24 +13,29 @@ clean-local:
 
 check:
 	@if [ "$(PYTHON)" = ":" ] ; then                                                      \
-                echo "Python not found, not able to execute system tests." ;                  \
-                exit 1 ;                                                                      \
-        else                                                                                  \
-                if [ "x$(HAS_ROBOT)" = "xno" ] ; then                                         \
-                        echo "Robot Framework not found, not able to execute system tests." ; \
-                        exit 1 ;                                                              \
-                else                                                                          \
-                        echo "Checking systemtests UT's..." ;                                 \
-                        $(PYTHON) -m unittest discover -v $(SYSTEMTESTS_SRC_DIR) ;            \
-                                                                                              \
-                        echo "Running systemtests..." ;                                       \
-                        $(ROBOT) -d $(SYSTEMTESTS_LOGS_DIR)                                   \
-                                 --variable SUT_PATH:$(top_builddir)/src/omtt                 \
-                                 --variable OMTT_TESTS_DIR:$(SYSTEMTESTS_SRC_DIR)/omtt        \
-                                 --variable HELPER_APPS_DIR:$(SYSTEMTESTS_BUILD_DIR)/apps     \
-                                 -L DEBUG                                                     \
-                                 $(SYSTEMTESTS_SRC_DIR) ;                                     \
-                fi                                                                            \
-        fi
+		echo "Python not found, not able to execute system tests." ;                  \
+		exit 1 ;                                                                      \
+	fi
+
+	@if [ "x$(HAS_PYTHON_UNITTEST)" = "xno" ] ; then                                      \
+		echo "Python Unittest module not found, not able to execute system tests." ;  \
+		exit 1 ;                                                                      \
+	fi
+
+	@if [ "x$(HAS_ROBOT)" = "xno" ] ; then                                                \
+		echo "Robot Framework not found, not able to execute system tests." ;         \
+		exit 1 ;                                                                      \
+	fi
+
+	echo "Checking systemtests UT's..." ;
+	$(PYTHON) -m unittest discover -v $(SYSTEMTESTS_SRC_DIR) ;
+
+	echo "Running systemtests..." ;
+	$(ROBOT) -d $(SYSTEMTESTS_LOGS_DIR)                                   \
+		 --variable SUT_PATH:$(top_builddir)/src/omtt                 \
+		 --variable OMTT_TESTS_DIR:$(SYSTEMTESTS_SRC_DIR)/omtt        \
+		 --variable HELPER_APPS_DIR:$(SYSTEMTESTS_BUILD_DIR)/apps     \
+		 -L DEBUG                                                     \
+		 $(SYSTEMTESTS_SRC_DIR) ;
 
 .PHONY: check
